export const theme = {
  color: {
    surface: '#F7F7F6',
    onSurface: '#1A1C1A',
    surfaceSecondary: '#FFFFFF',
    onSurfaceSecondary: '#1A1C1A',
    surfaceTertiary: '#EAEAE8',
    onSurfaceTertiary: '#4A4D4A',
    surfaceInverse: '#2C302C',
    onSurfaceInverse: '#F7F7F6',
    brand: '#5E8166',
    brandPrimary: '#5E8166',
    onBrandPrimary: '#FFFFFF',
    brandSecondary: '#A3BCA7',
    onBrandSecondary: '#1A1C1A',
    brandTertiary: '#D1DFD4',
    onBrandTertiary: '#2E4233',
    success: '#4A7A59',
    onSuccess: '#FFFFFF',
    warning: '#E59A54',
    onWarning: '#1A1C1A',
    error: '#C95D5D',
    onError: '#FFFFFF',
    info: '#4A707A',
    onInfo: '#FFFFFF',
    border: '#E5E5E3',
    borderStrong: '#C2C2C0',
    divider: '#EAEAE8',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    '2xl': 32,
    '3xl': 48,
  },
  radius: {
    sm: 6,
    md: 12,
    lg: 20,
    pill: 999,
  },
  text: {
    sm: 12,
    base: 14,
    lg: 16,
    xl: 20,
    '2xl': 24,
  },
};
